<?php

namespace Database\Seeders;

use App\Models\Vendor;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = [
            [
                'rfc' => 'GAMP850101AB1',
                'business_name' => 'Papelería y Oficina del Centro SA de CV',
                'contact_name' => 'María García López',
                'email' => 'ventas@papeleriacentro.com.mx',
                'phone' => '3312345678',
                'address' => 'Av. Juárez 450, Col. Centro',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'zip_code' => '44100',
            ],
            [
                'rfc' => 'TSI090515KL3',
                'business_name' => 'Tecnología y Sistemas Integrales SA de CV',
                'contact_name' => 'Roberto Hernández Martínez',
                'email' => 'contacto@tsi-mexico.com',
                'phone' => '8187654321',
                'address' => 'Blvd. Díaz Ordaz 123, Col. Santa María',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'zip_code' => '64650',
            ],
            [
                'rfc' => 'LIM120320QW7',
                'business_name' => 'Limpieza Industrial Mexicana SA de CV',
                'contact_name' => 'Ana Sofía Ramírez',
                'email' => 'info@limpieza-industrial.mx',
                'phone' => '5556781234',
                'address' => 'Calle Reforma 789, Col. Polanco',
                'city' => 'Ciudad de México',
                'state' => 'Ciudad de México',
                'zip_code' => '11560',
            ],
            [
                'rfc' => 'CDS180901HN5',
                'business_name' => 'Consultoría y Desarrollo de Software SC',
                'contact_name' => 'Carlos Mendoza Ruiz',
                'email' => 'carlos@cds-consultores.com',
                'phone' => '4422334455',
                'address' => 'Av. Tecnológico 500, Col. San Pablo',
                'city' => 'Querétaro',
                'state' => 'Querétaro',
                'zip_code' => '76130',
            ],
            [
                'rfc' => 'SEG150715MX2',
                'business_name' => 'Seguridad Empresarial del Golfo SA de CV',
                'contact_name' => 'Luis Fernando Torres',
                'email' => 'lfernando@seg-golfo.com.mx',
                'phone' => '2291122334',
                'address' => 'Av. Costa Verde 321, Col. Boca del Río',
                'city' => 'Veracruz',
                'state' => 'Veracruz',
                'zip_code' => '94299',
            ],
            [
                'rfc' => 'MPC200301AB8',
                'business_name' => 'Material y Papelería Corporativa SA de CV',
                'contact_name' => 'Patricia Vega Sánchez',
                'email' => 'ventas@mpc-corp.mx',
                'phone' => '3336789012',
                'address' => 'Calle López Mateos 1200',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'zip_code' => '44600',
            ],
            [
                'rfc' => 'LOPH880512RT4',
                'business_name' => 'López & Asociados Contadores Públicos SC',
                'contact_name' => 'Héctor López Pérez',
                'email' => 'hlopez@lopezcontadores.com',
                'phone' => '5543218765',
                'address' => 'Insurgentes Sur 1602, Col. Crédito Constructor',
                'city' => 'Ciudad de México',
                'state' => 'Ciudad de México',
                'zip_code' => '03940',
            ],
            [
                'rfc' => 'DGR170622LM9',
                'business_name' => 'Diseño Gráfico Creativo SA de CV',
                'contact_name' => 'Diana Estrada Morales',
                'email' => 'diana@dgr-creativo.com',
                'phone' => '2224567890',
                'address' => 'Calle 5 de Mayo 890, Col. Centro',
                'city' => 'Puebla',
                'state' => 'Puebla',
                'zip_code' => '72000',
            ],
            [
                'rfc' => 'TEL110830NP6',
                'business_name' => 'Telecomunicaciones del Norte SA de CV',
                'contact_name' => 'Javier Cantú Garza',
                'email' => 'jcantu@telnorte.mx',
                'phone' => '8143215678',
                'address' => 'Av. Constitución 2500',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'zip_code' => '64000',
            ],
            [
                'rfc' => 'MTO190415XY1',
                'business_name' => 'Mantenimiento Total de Occidente SA de CV',
                'contact_name' => 'Sergio Navarro Ibarra',
                'email' => 'sergio@mto-occidente.com',
                'phone' => '3318765432',
                'address' => 'Periférico Sur 4500',
                'city' => 'Zapopan',
                'state' => 'Jalisco',
                'zip_code' => '45070',
            ],
            [
                'rfc' => 'SLG160908KH3',
                'business_name' => 'Servicios Logísticos Globales SA de CV',
                'contact_name' => 'Andrea Ríos Salazar',
                'email' => 'arios@slg-logistica.com.mx',
                'phone' => '5578901234',
                'address' => 'Calz. de Tlalpan 3000, Col. Coapa',
                'city' => 'Ciudad de México',
                'state' => 'Ciudad de México',
                'zip_code' => '14390',
            ],
            [
                'rfc' => 'CAP140205PQ5',
                'business_name' => 'Capacitación Profesional del Bajío SC',
                'contact_name' => 'Francisco Delgado Arias',
                'email' => 'fdelgado@capbajio.edu.mx',
                'phone' => '4771234567',
                'address' => 'Blvd. Campestre 200, Col. Jardines del Moral',
                'city' => 'León',
                'state' => 'Guanajuato',
                'zip_code' => '37160',
            ],
            [
                'rfc' => 'EMP210701WZ8',
                'business_name' => 'Empaques y Materiales del Pacífico SA de CV',
                'contact_name' => 'Gabriela Ochoa Lara',
                'email' => 'gochoa@empac-pacifico.com',
                'phone' => '6621098765',
                'address' => 'Blvd. Kino 800, Col. Country Club',
                'city' => 'Hermosillo',
                'state' => 'Sonora',
                'zip_code' => '83010',
            ],
            [
                'rfc' => 'REN130420DF2',
                'business_name' => 'Renta de Equipos del Norte SA de CV',
                'contact_name' => 'Eduardo Chávez Soto',
                'email' => 'echavez@rentaequipos.mx',
                'phone' => '6144567890',
                'address' => 'Av. Tecnológico 1500',
                'city' => 'Chihuahua',
                'state' => 'Chihuahua',
                'zip_code' => '31310',
            ],
            [
                'rfc' => 'ALS191115TG4',
                'business_name' => 'Alimentos y Servicios del Sureste SA de CV',
                'contact_name' => 'Verónica Pool Chan',
                'email' => 'vpool@alsureste.com.mx',
                'phone' => '9993456789',
                'address' => 'Calle 60 #400, Col. Centro',
                'city' => 'Mérida',
                'state' => 'Yucatán',
                'zip_code' => '97000',
            ],
        ];

        foreach ($vendors as $vendor) {
            Vendor::create($vendor);
        }
    }
}
